### ISSUE TITLE
"Stemming algorithm 'arabic' not found" in python!

### ISSUE THREAD

**Issue by Somino** [assem-ch/arabicstemmer#21]
The Arabic language is not included in the  [Assem's Arabic Light Stemmer](http://www.arabicstemmer.com) 
I tried that code (after I downloaded it )
`from snowballstemmer import stemmer`
`ar_stemmer = stemmer("arabic")`
`ar_stemmer.stemWord(u"فسميتموها")`
I get this error message : 

> raise KeyError("Stemming algorithm '%s' not found" % lang)

> KeyError:  "Stemming algorithm 'arabic' not found"

**Comment by Somino** [comment]
The problem is I installed the version 1.2.1 of snowballstemmer instead of 1.1.0

**Comment by assem-ch** [comment]
@Somino Thank you @Somino for feedback
