### ISSUE TITLE
Adding JS bundle to npm

### ISSUE THREAD

**Issue by goglue** [assem-ch/arabicstemmer#36]
The JS library is not published on npm, the client should manually download the source code and append it to the project, which of-course will cause for the client to lose the updates if there were any.

**Comment by assem-ch** [comment]
@goglue thanks for reporting, I will try to publish and maintain the js lib on npm

**Comment by LBenzahia** [comment]
@goglue, You can use it from [node-snowball](https://www.npmjs.com/package/node-snowball) npm package.

**Comment by assem-ch** [comment]
@LBenzahia that is following the version of stemmer in snowball repo

**Comment by LBenzahia** [comment]
@assem-ch , I think yes

**Comment by goglue** [comment]
@assem-ch @LBenzahia thank you guys for the support, I will close the issue for now 👍
